name: Deploy React App to Lightsail

on:
  push:
    branches:
      - master  # Change if you use a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.LIGHTSAIL_PEM }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy Build Files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key_path: ~/.ssh/id_rsa
          source: "build/"
          target: "/var/www/react-app/build"
          strip_components: 1

      - name: Reload NGINX via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key_path: ~/.ssh/id_rsa
          script: |
            sudo systemctl reload nginx
