name: Deploy React Vite App to Lightsail

on:
  push:
    branches:
      - master  # Adjust if you use a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Vite App
        run: npm run build

      - name: List Build Files
        run: ls -la dist/

      # Optional: Configure known_hosts for SSH (ensures the host is recognized)
      - name: Setup SSH known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.LIGHTSAIL_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Build Files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: "${{ secrets.LIGHTSAIL_PEM }}"
          source: "dist/"
          target: "/home/ubuntu/react-app/dist"
          strip_components: 1

      - name: Reload NGINX via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: "${{ secrets.LIGHTSAIL_PEM }}"
          script: |
            sudo systemctl reload nginx && sudo systemctl restart nginx
